#!/bin/bash
#############################################################################
# Siri Launcher Script
#############################################################################

PROJECT_DIR="$HOME/activi-dev-repos/super-mac-assistant"

# Terminal öffnen und Siri starten
osascript -e "
tell application \"Terminal\"
    activate
    do script \"cd $PROJECT_DIR && source venv/bin/activate && python3 src/siri_assistant.py\"
end tell
"
